/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicOrderRouteImport } from './routes/api/public/order'
import { Route as ApiPublicLeadRouteImport } from './routes/api/public/lead'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOrderRoute = ApiPublicOrderRouteImport.update({
  id: '/api/public/order',
  path: '/api/public/order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadRoute = ApiPublicLeadRouteImport.update({
  id: '/api/public/lead',
  path: '/api/public/lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/lead': typeof ApiPublicLeadRoute
  '/api/public/order': typeof ApiPublicOrderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/lead': typeof ApiPublicLeadRoute
  '/api/public/order': typeof ApiPublicOrderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/lead': typeof ApiPublicLeadRoute
  '/api/public/order': typeof ApiPublicOrderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/health'
    | '/api/public/lead'
    | '/api/public/order'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/health' | '/api/public/lead' | '/api/public/order'
  id:
    | '__root__'
    | '/'
    | '/api/public/health'
    | '/api/public/lead'
    | '/api/public/order'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicLeadRoute: typeof ApiPublicLeadRoute
  ApiPublicOrderRoute: typeof ApiPublicOrderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/order': {
      id: '/api/public/order'
      path: '/api/public/order'
      fullPath: '/api/public/order'
      preLoaderRoute: typeof ApiPublicOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lead': {
      id: '/api/public/lead'
      path: '/api/public/lead'
      fullPath: '/api/public/lead'
      preLoaderRoute: typeof ApiPublicLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicLeadRoute: ApiPublicLeadRoute,
  ApiPublicOrderRoute: ApiPublicOrderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
